#############################################################################
# Makefile for building: NeoStore
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  RitualStore.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile RitualStore.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/libdtk-2.0.16/DWidget -isystem /usr/include/libdtk-2.0.16/DCore -isystem /usr/local/include/libqapt -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = NeoStore1.0.0
DISTDIR = /home/nicolas/RitualStore/.tmp/NeoStore1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -ldebconf-kde -lKF5CoreAddons -lKF5KIOCore -ldtkwidget -ldtkcore -L/usr/local/lib -lQApt -lQt5Widgets -lQt5Gui -lQt5Network -lQt5DBus -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = NextUIInterface.cpp \
		about.cpp \
		appcomponent.cpp \
		bookpage.cpp \
		categories.cpp \
		components.cpp \
		contentdownloader.cpp \
		downloadarea.cpp \
		downloadhandler.cpp \
		downloadpage.cpp \
		dtitlebar.cpp \
		flowlayout.cpp \
		installedpackagesview.cpp \
		localfilter.cpp \
		lookupobj.cpp \
		main.cpp \
		mainview.cpp \
		ndeclarative.cpp \
		packageview.cpp \
		screenshotwidget.cpp \
		secondui.cpp \
		servicemanager.cpp \
		start.cpp \
		textprogressbar.cpp \
		tools.cpp \
		toolsview.cpp qrc_main.cpp \
		moc_NextUIInterface.cpp \
		moc_about.cpp \
		moc_appcomponent.cpp \
		moc_bookpage.cpp \
		moc_categories.cpp \
		moc_components.cpp \
		moc_contentdownloader.cpp \
		moc_downloadarea.cpp \
		moc_downloadhandler.cpp \
		moc_downloadpage.cpp \
		moc_installedpackagesview.cpp \
		moc_localfilter.cpp \
		moc_lookupobj.cpp \
		moc_mainview.cpp \
		moc_ndeclarative.cpp \
		moc_packageview.cpp \
		moc_screenshotwidget.cpp \
		moc_secondui.cpp \
		moc_start.cpp \
		moc_tools.cpp \
		moc_toolsview.cpp
OBJECTS       = NextUIInterface.o \
		about.o \
		appcomponent.o \
		bookpage.o \
		categories.o \
		components.o \
		contentdownloader.o \
		downloadarea.o \
		downloadhandler.o \
		downloadpage.o \
		dtitlebar.o \
		flowlayout.o \
		installedpackagesview.o \
		localfilter.o \
		lookupobj.o \
		main.o \
		mainview.o \
		ndeclarative.o \
		packageview.o \
		screenshotwidget.o \
		secondui.o \
		servicemanager.o \
		start.o \
		textprogressbar.o \
		tools.o \
		toolsview.o \
		qrc_main.o \
		moc_NextUIInterface.o \
		moc_about.o \
		moc_appcomponent.o \
		moc_bookpage.o \
		moc_categories.o \
		moc_components.o \
		moc_contentdownloader.o \
		moc_downloadarea.o \
		moc_downloadhandler.o \
		moc_downloadpage.o \
		moc_installedpackagesview.o \
		moc_localfilter.o \
		moc_lookupobj.o \
		moc_mainview.o \
		moc_ndeclarative.o \
		moc_packageview.o \
		moc_screenshotwidget.o \
		moc_secondui.o \
		moc_start.o \
		moc_tools.o \
		moc_toolsview.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ComposerEditorNG.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_EventViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_FollowupReminder.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KChart.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KdepimDBusInterfaces.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDGantt2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KManageSieve.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSieve.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSieveUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwidget.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwm.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_ftp.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_ftp_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageList.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QApt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SendLater.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RitualStore.pro NextUIInterface.h \
		about.h \
		appcomponent.h \
		bookpage.h \
		categories.h \
		components.h \
		contentdownloader.h \
		dapplication_p.h \
		downloadarea.h \
		downloadhandler.h \
		downloadpage.h \
		dtitlebar.h \
		flowlayout.h \
		installedpackagesview.h \
		localfilter.h \
		lookupobj.h \
		mainview.h \
		ndeclarative.h \
		packageview.h \
		screenshotwidget.h \
		secondui.h \
		servicemanager.h \
		start.h \
		textprogressbar.h \
		tools.h \
		toolsview.h NextUIInterface.cpp \
		about.cpp \
		appcomponent.cpp \
		bookpage.cpp \
		categories.cpp \
		components.cpp \
		contentdownloader.cpp \
		downloadarea.cpp \
		downloadhandler.cpp \
		downloadpage.cpp \
		dtitlebar.cpp \
		flowlayout.cpp \
		installedpackagesview.cpp \
		localfilter.cpp \
		lookupobj.cpp \
		main.cpp \
		mainview.cpp \
		ndeclarative.cpp \
		packageview.cpp \
		screenshotwidget.cpp \
		secondui.cpp \
		servicemanager.cpp \
		start.cpp \
		textprogressbar.cpp \
		tools.cpp \
		toolsview.cpp
QMAKE_TARGET  = NeoStore
DESTDIR       = 
TARGET        = NeoStore


first: all
####### Build rules

$(TARGET): ui_about.h ui_appcomponent.h ui_bookpage.h ui_categories.h ui_components.h ui_downloadarea.h ui_downloadpage.h ui_lookupobj.h ui_mainview.h ui_packageview.h ui_screenshotwidget.h ui_secondui.h ui_start.h ui_installedpackagesview.h ui_tools.h ui_toolsview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RitualStore.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ComposerEditorNG.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_EventViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_FollowupReminder.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KChart.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KdepimDBusInterfaces.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDGantt2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KManageSieve.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSieve.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSieveUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwidget.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwm.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_ftp.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_ftp_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageList.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QApt.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SendLater.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RitualStore.pro \
		main.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5DBus.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile RitualStore.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiSocialUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_CalendarSupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ComposerEditorNG.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_EventViews.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_FollowupReminder.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_GrantleeTheme.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Gravatar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_IncidenceEditor.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KaddressbookGrantlee.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBlog.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KChart.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KContacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KdepimDBusInterfaces.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDGantt2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPICore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGAPITasks.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIMAP.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Kirigami.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJS.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KManageSieve.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KMime.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KPty.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSieve.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSieveUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KTNef.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Ldap.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwidget.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkwm.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_ftp.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_ftp_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Libkdepim.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Libkleo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MailCommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MailImporter.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Mbox.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageComposer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageList.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_MessageViewer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_PimCommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QApt.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SendLater.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Syndication.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_TemplateParser.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
RitualStore.pro:
main.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5DBus.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile RitualStore.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.qrc $(DISTDIR)/
	$(COPY_FILE) --parents NextUIInterface.h about.h appcomponent.h bookpage.h categories.h components.h contentdownloader.h dapplication_p.h downloadarea.h downloadhandler.h downloadpage.h dtitlebar.h flowlayout.h installedpackagesview.h localfilter.h lookupobj.h mainview.h ndeclarative.h packageview.h screenshotwidget.h secondui.h servicemanager.h start.h textprogressbar.h tools.h toolsview.h $(DISTDIR)/
	$(COPY_FILE) --parents NextUIInterface.cpp about.cpp appcomponent.cpp bookpage.cpp categories.cpp components.cpp contentdownloader.cpp downloadarea.cpp downloadhandler.cpp downloadpage.cpp dtitlebar.cpp flowlayout.cpp installedpackagesview.cpp localfilter.cpp lookupobj.cpp main.cpp mainview.cpp ndeclarative.cpp packageview.cpp screenshotwidget.cpp secondui.cpp servicemanager.cpp start.cpp textprogressbar.cpp tools.cpp toolsview.cpp $(DISTDIR)/
	$(COPY_FILE) --parents about.ui appcomponent.ui bookpage.ui categories.ui components.ui downloadarea.ui downloadpage.ui lookupobj.ui mainview.ui packageview.ui screenshotwidget.ui secondui.ui start.ui installedpackagesview.ui tools.ui toolsview.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_main.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_main.cpp
qrc_main.cpp: main.qrc \
		/usr/lib/x86_64-linux-gnu/qt5/bin/rcc \
		mybg.svgz \
		logo.png \
		mybg.png \
		banner.png \
		mybg.svg \
		Staatliches-Regular.ttf \
		contrib/kde.svg \
		contrib/fontawesome.svg \
		contrib/qt.png \
		contrib/deepin.svg \
		styles/ndeclarative.qtreeview.css \
		icons/sync-alt-solid.svg \
		icons/archive-solid.svg \
		icons/arrow-alt-circle-down-solid.svg \
		icons/arrow-alt-circle-up-solid.svg \
		icons/box-open-solid.svg \
		icons/check-solid.svg \
		icons/address-card-solid.svg \
		icons/redo-alt-solid.svg \
		icons/undo-alt-solid.svg \
		icons/heart-broken-solid.svg \
		icons/tools-solid.svg \
		icons/trash-restore-solid.svg \
		icons/hat-cowboy-side-solid.svg \
		icons/save-solid.svg \
		icons/broom-solid.svg \
		icons/pen-solid.svg \
		icons/star-solid.svg \
		icons/chevron-right-solid.svg \
		icons/qtreeview/branch-closed.png \
		icons/qtreeview/vline.png \
		icons/qtreeview/branch-open.png \
		icons/qtreeview/branch-end.png \
		icons/qtreeview/branch-more.png \
		icons/numbers/3.svg \
		icons/numbers/7.svg \
		icons/numbers/2.svg \
		icons/numbers/10.svg \
		icons/numbers/6.svg \
		icons/numbers/1.svg \
		icons/numbers/5.svg \
		icons/numbers/9.svg \
		icons/numbers/more.svg \
		icons/numbers/4.svg \
		icons/numbers/8.svg
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name main main.qrc -o qrc_main.cpp

compiler_moc_header_make_all: moc_NextUIInterface.cpp moc_about.cpp moc_appcomponent.cpp moc_bookpage.cpp moc_categories.cpp moc_components.cpp moc_contentdownloader.cpp moc_downloadarea.cpp moc_downloadhandler.cpp moc_downloadpage.cpp moc_dtitlebar.cpp moc_installedpackagesview.cpp moc_localfilter.cpp moc_lookupobj.cpp moc_mainview.cpp moc_ndeclarative.cpp moc_packageview.cpp moc_screenshotwidget.cpp moc_secondui.cpp moc_start.cpp moc_tools.cpp moc_toolsview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_NextUIInterface.cpp moc_about.cpp moc_appcomponent.cpp moc_bookpage.cpp moc_categories.cpp moc_components.cpp moc_contentdownloader.cpp moc_downloadarea.cpp moc_downloadhandler.cpp moc_downloadpage.cpp moc_dtitlebar.cpp moc_installedpackagesview.cpp moc_localfilter.cpp moc_lookupobj.cpp moc_mainview.cpp moc_ndeclarative.cpp moc_packageview.cpp moc_screenshotwidget.cpp moc_secondui.cpp moc_start.cpp moc_tools.cpp moc_toolsview.cpp
moc_NextUIInterface.cpp: NextUIInterface.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include NextUIInterface.h -o moc_NextUIInterface.cpp

moc_about.cpp: about.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include about.h -o moc_about.cpp

moc_appcomponent.cpp: appcomponent.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include appcomponent.h -o moc_appcomponent.cpp

moc_bookpage.cpp: components.h \
		flowlayout.h \
		appcomponent.h \
		bookpage.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include bookpage.h -o moc_bookpage.cpp

moc_categories.cpp: categoryitem.h \
		categories.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include categories.h -o moc_categories.cpp

moc_components.cpp: flowlayout.h \
		appcomponent.h \
		components.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include components.h -o moc_components.cpp

moc_contentdownloader.cpp: start.h \
		mainview.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		contentdownloader.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include contentdownloader.h -o moc_contentdownloader.cpp

moc_downloadarea.cpp: downloadarea.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include downloadarea.h -o moc_downloadarea.cpp

moc_downloadhandler.cpp: textprogressbar.h \
		downloadhandler.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include downloadhandler.h -o moc_downloadhandler.cpp

moc_downloadpage.cpp: mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		downloadpage.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include downloadpage.h -o moc_downloadpage.cpp

moc_dtitlebar.cpp: dtitlebar.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dtitlebar.h -o moc_dtitlebar.cpp

moc_installedpackagesview.cpp: installedpackagesview.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include installedpackagesview.h -o moc_installedpackagesview.cpp

moc_localfilter.cpp: localfilter.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include localfilter.h -o moc_localfilter.cpp

moc_lookupobj.cpp: lookupobj.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include lookupobj.h -o moc_lookupobj.cpp

moc_mainview.cpp: start.h \
		packageview.h \
		mainview.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		screenshotwidget.h \
		mainview.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainview.h -o moc_mainview.cpp

moc_ndeclarative.cpp: ndeclarative.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ndeclarative.h -o moc_ndeclarative.cpp

moc_packageview.cpp: mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		packageview.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include packageview.h -o moc_packageview.cpp

moc_screenshotwidget.cpp: screenshotwidget.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include screenshotwidget.h -o moc_screenshotwidget.cpp

moc_secondui.cpp: mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		secondui.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include secondui.h -o moc_secondui.cpp

moc_start.cpp: start.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include start.h -o moc_start.cpp

moc_tools.cpp: tools.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tools.h -o moc_tools.cpp

moc_toolsview.cpp: mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		toolsview.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nicolas/RitualStore -I/usr/include/libdtk-2.0.16/DWidget -I/usr/include/libdtk-2.0.16/DCore -I/usr/local/include/libqapt -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets/5.7.1/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtGui/5.7.1/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1 -I/usr/include/x86_64-linux-gnu/qt5/QtCore/5.7.1/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include toolsview.h -o moc_toolsview.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_about.h ui_appcomponent.h ui_bookpage.h ui_categories.h ui_components.h ui_downloadarea.h ui_downloadpage.h ui_lookupobj.h ui_mainview.h ui_packageview.h ui_screenshotwidget.h ui_secondui.h ui_start.h ui_installedpackagesview.h ui_tools.h ui_toolsview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_about.h ui_appcomponent.h ui_bookpage.h ui_categories.h ui_components.h ui_downloadarea.h ui_downloadpage.h ui_lookupobj.h ui_mainview.h ui_packageview.h ui_screenshotwidget.h ui_secondui.h ui_start.h ui_installedpackagesview.h ui_tools.h ui_toolsview.h
ui_about.h: about.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic about.ui -o ui_about.h

ui_appcomponent.h: appcomponent.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic appcomponent.ui -o ui_appcomponent.h

ui_bookpage.h: bookpage.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic bookpage.ui -o ui_bookpage.h

ui_categories.h: categories.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic categories.ui -o ui_categories.h

ui_components.h: components.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic components.ui -o ui_components.h

ui_downloadarea.h: downloadarea.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic downloadarea.ui -o ui_downloadarea.h

ui_downloadpage.h: downloadpage.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic downloadpage.ui -o ui_downloadpage.h

ui_lookupobj.h: lookupobj.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic lookupobj.ui -o ui_lookupobj.h

ui_mainview.h: mainview.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainview.ui -o ui_mainview.h

ui_packageview.h: packageview.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic packageview.ui -o ui_packageview.h

ui_screenshotwidget.h: screenshotwidget.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic screenshotwidget.ui -o ui_screenshotwidget.h

ui_secondui.h: secondui.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic secondui.ui -o ui_secondui.h

ui_start.h: start.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic start.ui -o ui_start.h

ui_installedpackagesview.h: installedpackagesview.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic installedpackagesview.ui -o ui_installedpackagesview.h

ui_tools.h: tools.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic tools.ui -o ui_tools.h

ui_toolsview.h: toolsview.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic toolsview.ui -o ui_toolsview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

NextUIInterface.o: NextUIInterface.cpp NextUIInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NextUIInterface.o NextUIInterface.cpp

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

appcomponent.o: appcomponent.cpp appcomponent.h \
		ui_appcomponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appcomponent.o appcomponent.cpp

bookpage.o: bookpage.cpp bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		ui_bookpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookpage.o bookpage.cpp

categories.o: categories.cpp categories.h \
		categoryitem.h \
		ui_categories.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o categories.o categories.cpp

components.o: components.cpp components.h \
		flowlayout.h \
		appcomponent.h \
		ui_components.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o components.o components.cpp

contentdownloader.o: contentdownloader.cpp contentdownloader.h \
		start.h \
		mainview.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		downloadhandler.h \
		textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contentdownloader.o contentdownloader.cpp

downloadarea.o: downloadarea.cpp downloadarea.h \
		ui_downloadarea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadarea.o downloadarea.cpp

downloadhandler.o: downloadhandler.cpp downloadhandler.h \
		textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadhandler.o downloadhandler.cpp

downloadpage.o: downloadpage.cpp downloadpage.h \
		mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		ui_downloadpage.h \
		installedpackagesview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadpage.o downloadpage.cpp

dtitlebar.o: dtitlebar.cpp dtitlebar.h \
		dapplication_p.h \
		moc_dtitlebar.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dtitlebar.o dtitlebar.cpp

flowlayout.o: flowlayout.cpp flowlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowlayout.o flowlayout.cpp

installedpackagesview.o: installedpackagesview.cpp installedpackagesview.h \
		ui_installedpackagesview.h \
		mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o installedpackagesview.o installedpackagesview.cpp

localfilter.o: localfilter.cpp localfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localfilter.o localfilter.cpp

lookupobj.o: lookupobj.cpp lookupobj.h \
		ui_lookupobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lookupobj.o lookupobj.cpp

main.o: main.cpp mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainview.o: mainview.cpp mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		ui_mainview.h \
		downloadpage.h \
		ndeclarative.h \
		about.h \
		contentdownloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainview.o mainview.cpp

ndeclarative.o: ndeclarative.cpp ndeclarative.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ndeclarative.o ndeclarative.cpp

packageview.o: packageview.cpp packageview.h \
		mainview.h \
		start.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		screenshotwidget.h \
		ui_packageview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packageview.o packageview.cpp

screenshotwidget.o: screenshotwidget.cpp screenshotwidget.h \
		ui_screenshotwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screenshotwidget.o screenshotwidget.cpp

secondui.o: secondui.cpp secondui.h \
		mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		downloadarea.h \
		toolsview.h \
		dtitlebar.h \
		ui_secondui.h \
		localfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o secondui.o secondui.cpp

servicemanager.o: servicemanager.cpp servicemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servicemanager.o servicemanager.cpp

start.o: start.cpp start.h \
		ui_start.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o start.o start.cpp

textprogressbar.o: textprogressbar.cpp textprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textprogressbar.o textprogressbar.cpp

tools.o: tools.cpp tools.h \
		ui_tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

toolsview.o: toolsview.cpp toolsview.h \
		mainview.h \
		start.h \
		packageview.h \
		screenshotwidget.h \
		bookpage.h \
		components.h \
		flowlayout.h \
		appcomponent.h \
		categories.h \
		categoryitem.h \
		secondui.h \
		downloadarea.h \
		dtitlebar.h \
		ui_toolsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolsview.o toolsview.cpp

qrc_main.o: qrc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_main.o qrc_main.cpp

moc_NextUIInterface.o: moc_NextUIInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NextUIInterface.o moc_NextUIInterface.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_appcomponent.o: moc_appcomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appcomponent.o moc_appcomponent.cpp

moc_bookpage.o: moc_bookpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bookpage.o moc_bookpage.cpp

moc_categories.o: moc_categories.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_categories.o moc_categories.cpp

moc_components.o: moc_components.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_components.o moc_components.cpp

moc_contentdownloader.o: moc_contentdownloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contentdownloader.o moc_contentdownloader.cpp

moc_downloadarea.o: moc_downloadarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadarea.o moc_downloadarea.cpp

moc_downloadhandler.o: moc_downloadhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadhandler.o moc_downloadhandler.cpp

moc_downloadpage.o: moc_downloadpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadpage.o moc_downloadpage.cpp

moc_installedpackagesview.o: moc_installedpackagesview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_installedpackagesview.o moc_installedpackagesview.cpp

moc_localfilter.o: moc_localfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localfilter.o moc_localfilter.cpp

moc_lookupobj.o: moc_lookupobj.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lookupobj.o moc_lookupobj.cpp

moc_mainview.o: moc_mainview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainview.o moc_mainview.cpp

moc_ndeclarative.o: moc_ndeclarative.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ndeclarative.o moc_ndeclarative.cpp

moc_packageview.o: moc_packageview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_packageview.o moc_packageview.cpp

moc_screenshotwidget.o: moc_screenshotwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screenshotwidget.o moc_screenshotwidget.cpp

moc_secondui.o: moc_secondui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_secondui.o moc_secondui.cpp

moc_start.o: moc_start.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_start.o moc_start.cpp

moc_tools.o: moc_tools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tools.o moc_tools.cpp

moc_toolsview.o: moc_toolsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolsview.o moc_toolsview.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

