/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef NEXTUIINTERFACE_H
#define NEXTUIINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface nui.global
 */
class NuiGlobalInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "nui.global"; }

public:
    NuiGlobalInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~NuiGlobalInterface();

    Q_PROPERTY(QString TheTheme READ theTheme WRITE setTheTheme)
    inline QString theTheme() const
    { return qvariant_cast< QString >(property("TheTheme")); }
    inline void setTheTheme(const QString &value)
    { setProperty("TheTheme", QVariant::fromValue(value)); }

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void themeChanged();
};

namespace nui {
  typedef ::NuiGlobalInterface global;
}
#endif
