/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was:
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "SystemStarterCheckerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GlobalAdaptor
 */

GlobalAdaptor::GlobalAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GlobalAdaptor::~GlobalAdaptor()
{
    // destructor
}

QString GlobalAdaptor::theTheme() const
{
    // get the value of property TheTheme
    return qvariant_cast< QString >(parent()->property("TheTheme"));
}

void GlobalAdaptor::setTheTheme(const QString &value)
{
    // set the value of property TheTheme
    parent()->setProperty("TheTheme", QVariant::fromValue(value));
}

